---
title: "Zeus Project"
output: html_document
---
##AuxCopy
```{r fig.width=1, fig.height=1,echo=FALSE}
library(jpeg)
library(grid)
img <- readJPEG("C:/dati/generic/Zeus-0.jpg")
 grid.raster(img)
```

###Current Status Analysis

[Lon3 Current Status](http://10.2.210.104/lon3AUX.html)

[DFW1 Current Status](http://10.2.210.104/DFW1AUX.html)

###Long term analysis

[Lon3 Long term analysis](http://10.2.210.104/trendAUX.html)

[DFW1 Long term analysis](http://10.2.210.104/trendAUXDFW1.html)

##Job Analysis 
```{r fig.width=1, fig.height=1,echo=FALSE}
library(jpeg)
library(grid)
img <- readJPEG("C:/dati/generic/Zeus.jpg")
 grid.raster(img)
```

[Lon3 Jobs analysis per Commcells](http://10.2.210.104/TS_LON3Jobs.html)

##Pruning Analysis
```{r fig.width=1, fig.height=1,echo=FALSE}
library(jpeg)
library(grid)
img <- readJPEG("C:/dati/generic/3.jpg")
 grid.raster(img)
```

[Lon3 Prunning Current analysis -- Summary per Commcells](http://10.2.210.104/criticalSize.html)


[math notes](https://www.tug.org/texshowcase/cheat.pdf)
